blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    
    path('',views.all_blog,name='all_blog'),
    path('<int:blog_id>',views.details,name='details'),

    
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
	title = models.CharField(max_length=100)
	author = models.CharField(max_length=100)


	date = models.DateField(max_length=100)
	description = models.TextField(max_length=10000000000000000000000000000)



	def __str__(self):
		return self.title

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField(max_length=250)
	image = models.ImageField(upload_to='portfolio/images')
	url = models.URLField(blank=True)

	def __str__(self):
		return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Blog

# Create your views here.

def all_blog(request):
	blogs = Blog.objects.order_by('-date')

	return render(request, 'blog/all_blog.html', {'blogs': blogs})


def details(request, blog_id):
	blog = get_object_or_404(Blog, pk=blog_id)

	return render(request, 'blog/details.html', {'blog': blog})
 

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.

def home(request):
	projects = Project.objects.all()

	return render(request, 'portfolio/home.html', {'projects':projects})

blog/templates/blog/all_blog.html
{% extends 'portfolio/base.html' %}
{% block content %}

{% load static%}


	<h1>Abeed has added {{ blogs.count }} blog{{ blogs.count|pluralize }}</h1>

	 <br><br>
	{% for blog in blogs %}
	<a href="{% url 'blog:details' blog.id %}" ><h4>{{ blog.title|safe }}</h4> </a>
	{{ blog.author|safe }}<br>
	{{ blog.date|date:'M d'|upper }}       
	<h6>{{ blog.description|striptags|truncatechars:100 }}</h6> <br> <br>


	{% endfor %}
{% endblock %}

blog/templates/blog/details.html
{% extends 'portfolio/base.html' %}
{% block content %}

<center>
<div class="row">

	<div class="col-lg-4 col-md-6">
		<h4>{{ blog.title|safe }} </h4> <br>
		<h5>{{ blog.author|safe }}</h5><br>
		{{ blog.description|safe }}

	</div>
</div>
</center>
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <title></title>
</head>
<body>
  <div class="container">


<link rel="stylesheet" type="text/css" href="{% static 'portfolio/back.jpg' %}">
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <img src="{% static 'portfolio/bman.jpg' %}" height="50" width="60">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">Portfolio</a>
      <a class="nav-item nav-link" href="{% url 'blog:all_blog' %}">Blog</a>
      <a class="nav-item nav-link" href="{% static 'portfolio/naz1.pdf' %}" target="_blank">Book </a>
      
    </div>
  </div>
</nav>

  {% block content %}
  {% endblock %}

  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

{% load static %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/akash.jpg' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">akash</h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}